"""adding isAdmin column to users table

Revision ID: 8e050c391a73
Revises: 0904c6edfe21
Create Date: 2021-12-19 14:25:47.812197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e050c391a73'
down_revision = '0904c6edfe21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isAdmin', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'isAdmin')
    # ### end Alembic commands ###
